version: '3.7'

services:
    app:
        container_name: jourloy_telegram
        build:
            context: .
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run start:dev
        env_file:
            - .env
networks:
    back: